name: Pipeline CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USES }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: guilhermesilva33/meu-site-pudim:latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: guilhermesilva33/meu-site-pudim:latest 